osdk-core/api/src/dji_vehicle.cpp

See: https://github.com/dji-sdk/Onboard-SDK/issues/200

Fix arg passed to sizeof and fix array indices

---

osdk-core/api/inc/dji_mission_type.hpp
sample/platform/STM32/OnBoardSDK_STM32/User/MissionSample.cpp
sample/platform/linux/missions/mission_sample.cpp

2.change command_param's type from uint16 to int16
OSDK-2471

fixed:1.add note of WayPointSettings's command_list and command_param.

---

osdk-core/api/inc/dji_subscription.hpp

feat:add number of subscription package from 5 to 7

---

sample/platform/linux/advanced-sensing/camera_stream_target_tracking_sample/target_tracking.cpp

Fix compile issue of camera-stream-target-tracking-sample.

fix:fix compile issue of camera-stream-target-tracking-sample

---

osdk-core/api/src/dji_legacy_linker.cpp
osdk-core/api/src/dji_waypoint.cpp
sample/platform/linux/missions/mission_sample.cpp

fixed:fix setWaypointEventCallback fail problem.

---

osdk-core/api/src/dji_vehicle.cpp

fixed:replace isUSBPlugged with isUartplugged in heartbeat

---

sample/platform/linux/advanced-sensing/stereo_vision_new_sample/CMakeLists.txt
sample/platform/linux/advanced-sensing/stereo_vision_new_sample/main.cpp

Add new stereo new API sample.

new:add new stereo new API sample

---

sample/core/src/camera_manager_async_sample.cpp

Fix shoot single photo fail when interval shoot-photo mode

fix:fix shoot single photo fail when interval shoot-photo mode

---

osdk-core/advanced-sensing/api/src/dji_liveview_impl.cpp

Fix PSDK liveview getting issue

fix:fix PSDK liveview getting issue

---

osdk-core/api/src/dji_vehicle.cpp

fiexed:replace isUSBPlugged with isUartPlugged in heartbeat
OSDK-2566

fixed heatbeat problem

---

sample/platform/linux/payloads/main_sync.cpp

fix:fix payload sample typo

---

osdk-core/api/inc/dji_telemetry.hpp

fixed:add notes of deviceStatus.

---

osdk-core/modules/inc/payload/dji_camera_module.hpp

fix:fix compile issue for STM32

---

sample/core/src/camera_manager_async_sample.cpp
sample/core/src/camera_manager_sync_sample.cpp
sample/platform/linux/payloads/main_async.cpp
sample/platform/linux/payloads/main_sync.cpp

Fix sample code of camera parameters setting for Z30. If parameters are
got failed, the setting will still run.

fix:fix sample code of camera parameters setting

---

osdk-core/api/src/dji_waypoint_v2.cpp
sample/core/src/waypoint_v2_sample.cpp

fixed:fixed upload mission fail when doing waypointV2

---

osdk-core/modules/inc/filemgr/impl/dji_file_mgr_impl.hpp
osdk-core/modules/src/filemgr/dji_file_mgr_define.cpp
osdk-core/modules/src/filemgr/impl/dji_file_mgr_impl.cpp

Fix the name issues for the download function.

fix:fix the name issues for the download function

---

osdk-core/api/src/dji_waypoint_v2.cpp

fixed:fixed upload mission fail when stopping mission

---

sample/platform/STM32/OnBoardSDK_STM32/User/main.cpp

fix:fix log

---

osdk-core/advanced-sensing/api/src/dji_advanced_sensing.cpp
osdk-core/api/src/dji_vehicle.cpp

Fix running crash when exit. Fix an error log.

fix:fix running crash when exit

---

osdk-core/api/inc/dji_waypoint_v2.hpp
osdk-core/api/src/dji_waypoint_v2.cpp
osdk-core/linker/x86/inc/osdk_command.h
sample/core/src/waypoint_v2_sample.cpp

fixed:adapt to ros for waypointV2 event and state push

---

osdk-core/api/inc/dji_waypoint_v2.hpp
osdk-core/linker/x86/inc/osdk_command.h

Fix the compile issues because of the waypoint 2.0 on all platforms.

fix:fix the compile issues

---

osdk-core/modules/src/filemgr/impl/dji_file_mgr_impl.cpp
sample/platform/linux/mop/om_download_sample.cpp

fix:fix static check issues

---

osdk-core/api/inc/dji_waypoint_v2.hpp

fix:fix compile issues for ROS

---

sample/platform/linux/missions/main.cpp

docs:add note about waypoint1.0 mission just adapt to M210

---

README.md

Update README.md for OSDK 4.0.1

new:update README.md for OSDK 4.0.1

---

osdk-core/CMakeLists.txt

Add internal compilation settings for CI.

new:add internal compilation settings for CI

---

osdk-core/CMakeLists.txt

new:internal ci test debug

---

osdk-core/modules/inc/payload/dji_gimbal_module.hpp

fix:fix gimbal comment

---

osdk-core/api/src/dji_vehicle.cpp

Add retrying for activation to avoid the NEW_DEVICE_ERROR when
activating at the first time. Add log for activate async API.

new:add retrying for activation to avoid the NEW_DEVICE_ERROR

---

osdk-core/api/src/dji_waypoint_v2.cpp
sample/core/src/waypoint_v2_sample.cpp

fixed:fixed the problem of inversing waypointV2's X Y

---

osdk-core/modules/src/filemgr/impl/dji_file_mgr_impl.cpp

Fix camera download issues for PSDK

fix:fix camera download issues for PSDK

---

osdk-core/advanced-sensing/camera_stream/src/dji_camera_stream_decoder.cpp
osdk-core/advanced-sensing/camera_stream/src/dji_camera_stream_decoder.hpp

fix:lock the decoding process

---

osdk-core/api/inc/dji_broadcast.hpp

docs:the velocity of getVelocity only support ground frame

---

osdk-core/api/inc/dji_camera_manager.hpp
osdk-core/api/src/dji_camera_manager.cpp
osdk-core/modules/inc/payload/dji_camera_module.hpp
osdk-core/modules/src/payload/dji_camera_module.cpp
sample/core/src/camera_manager_sync_sample.cpp

Add APIs to get the version and firmware of payloads.

new:add APIs to get the version and firmware of payloads

---

osdk-core/api/inc/dji_camera_manager.hpp
osdk-core/api/src/dji_camera_manager.cpp
osdk-core/modules/inc/payload/dji_camera_module.hpp
osdk-core/modules/src/payload/dji_camera_module.cpp
sample/core/src/camera_manager_sync_sample.cpp

Fix get optizoom factor apis for H20, including the getting and setting
APIs.

fix:fix get optizoom factor APIs for H20

---

osdk-core/api/src/dji_vehicle.cpp
osdk-core/modules/inc/firewall/osdk_firewall.hpp
osdk-core/modules/src/firewall/osdk_firewall.cpp

Improve the firewall activate logic, decoupling from OSDK activate
logic.

new:improve the firewall activate logic

---

osdk-core/cmake-modules/FindLibUDEV.cmake
sample/platform/linux/CMakeLists.txt
sample/platform/linux/advanced-sensing/CMakeLists.txt
sample/platform/linux/battery/CMakeLists.txt
sample/platform/linux/flight-control/CMakeLists.txt
sample/platform/linux/hal/hotplug/osdkhal_hotplug.c
sample/platform/linux/hal/hotplug/osdkhal_hotplug.h
sample/platform/linux/hal/osdkhal_linux.c
sample/platform/linux/hms/CMakeLists.txt
sample/platform/linux/logging/CMakeLists.txt
sample/platform/linux/mfio/CMakeLists.txt
sample/platform/linux/missions/CMakeLists.txt
sample/platform/linux/mobile/CMakeLists.txt
sample/platform/linux/mop/CMakeLists.txt
sample/platform/linux/payload-3rd-party/CMakeLists.txt
sample/platform/linux/payloads/CMakeLists.txt
sample/platform/linux/telemetry/CMakeLists.txt
sample/platform/linux/time-sync/CMakeLists.txt

Add libudev finding rule for hotplug test

add:add libudev finding rule for hotplug test

---

osdk-core/modules/src/filemgr/impl/dji_file_mgr_impl.cpp

If H20 has more than 10~15 photos, the file name on the back will go wrong. Now fix it in the download implement.

fix:fix the incomplete download file list issue.

---

osdk-core/advanced-sensing/api/src/dji_liveview_impl.cpp
osdk-core/api/src/dji_camera_manager.cpp
osdk-core/api/src/dji_waypoint_v2.cpp
sample/platform/linux/hal/hotplug/osdkhal_hotplug.c
sample/platform/linux/hal/hotplug/osdkhal_hotplug.h
sample/platform/linux/hal/osdkhal_linux.c

Remove the useless logging.
Improve the logging of hotplug.

fix:fix logging

---

osdk-core/api/inc/dji_control.hpp
osdk-core/api/inc/dji_error.hpp
osdk-core/api/inc/dji_flight_controller.hpp
osdk-core/api/src/dji_control.cpp
osdk-core/api/src/dji_error.cpp
osdk-core/api/src/dji_flight_controller.cpp
osdk-core/modules/inc/flight/dji_flight_joystick_module.hpp
osdk-core/modules/inc/flight/dji_flight_link.hpp
osdk-core/modules/src/flight/dji_flight_joystick_module.cpp
osdk-core/modules/src/flight/dji_flight_link.cpp
sample/platform/linux/flight-control/flight_control_sample.cpp
sample/platform/linux/flight-control/main.cpp

feat:depulicated control class and perfect flightController class

---

osdk-core/modules/src/flight/dji_flight_joystick_module.cpp

fix:fix free memory api using

---

sample/core/inc/flight_sample.hpp
sample/core/src/flight_sample.cpp
sample/platform/linux/flight-control/flight_control_sample.cpp

fix:fixed not start global position broadcast when excuting position

---

osdk-core/api/inc/dji_flight_controller.hpp
osdk-core/api/src/dji_flight_controller.cpp
sample/core/inc/flight_sample.hpp
sample/core/src/flight_sample.cpp
sample/platform/linux/flight-control/main.cpp

feat:optimize velocity control

---

osdk-core/api/src/dji_flight_controller.cpp
sample/platform/linux/flight-control/main.cpp

fixed:remove emergencybrake time and add print for FC sample's d part

---

osdk-core/modules/src/payload/dji_camera_module.cpp

Fix STM32 platform compile issue

fix:fix STM32 platform compile issue

---

osdk-core/modules/src/flight/dji_flight_link.cpp
sample/platform/linux/flight-control/main.cpp

fixed:fixed obtainjoystickctrlauthoritysync problem

---

osdk-core/api/src/dji_legacy_linker.cpp
osdk-core/modules/src/firewall/osdk_firewall.cpp
osdk-core/modules/src/payload/dji_camera_module.cpp
sample/platform/STM32/OnBoardSDK_STM32/OS/FreeRTOSConfig_h_diff.patch

enh:adjust STM32 Task stack

---

sample/core/src/waypoint_v2_sample.cpp

fixed:fixed upload too many waypoint error

---

osdk-core/advanced-sensing/api/src/dji_liveview_impl.cpp
sample/platform/linux/payloads/main_async.cpp
sample/platform/linux/payloads/main_sync.cpp

Fix log for camera sample and liveview module.

enh:fix log

---

osdk-core/api/inc/dji_mission_type.hpp
osdk-core/api/src/dji_waypoint_v2.cpp

fixed:fixed uploadmission:exchange maxFlightSpeed and autoFlightSpeed

---

sample/platform/STM32/OnBoardSDK_STM32/User/FlightControlSample.cpp
sample/platform/STM32/OnBoardSDK_STM32/User/MobileSample.cpp

Fix:
1.Moblie sample add logging for reveive messege.
2.FlightControlSample fix delay time.

fix:fix STM32 sample

---

osdk-core/api/src/dji_hms.cpp
osdk-core/modules/src/filemgr/impl/dji_file_mgr_impl.cpp
sample/core/src/hms_sample.cpp

Fix HMS and Download log format in ARMV7.

fix:fix log for ARMV7 system

---

osdk-core/api/src/dji_waypoint_v2.cpp

fixed:fixed wp2.0 problem about get invalid takeoff altitude

---

osdk-core/api/inc/dji_mission_type.hpp
osdk-core/api/inc/dji_waypoint_v2_action.hpp
osdk-core/api/src/dji_waypoint_v2.cpp

fixed:delete reachpoint trigger

---

sample/core/src/waypoint_v2_sample.cpp

Fix memory leak of waypoint v2 sample.

fix:fix static check of memory leak

---

osdk-core/api/src/dji_hms_impl.cpp

feat:update OSDK hms version

---

sample/platform/linux/common/UserConfig.txt

Update acm_port defination in the default UserConfig.txt.

fix:fix default UserConfig.txt

---

README.md

Withdrawal of README.md from 4.1.0 to 4.0.1

fix:withdrawal of README.md

---

osdk-core/api/src/dji_waypoint_v2.cpp

fix:reverse X and Y in downloadMission of wp2.0

---

osdk-core/api/inc/dji_mission_type.hpp

NOTE:add damplingDistance note

---

osdk-core/advanced-sensing/ori-osdk-core/protocol/src/dji_protocol_base.cpp
osdk-core/advanced-sensing/platform/src/linux_usb_device.cpp

fix:fix cordump problem when run stereo_new_sample on virtual machine

---

osdk-core/modules/src/payload/dji_gimbal_module.cpp

TEST: test is ok
Signed-off-by: Martin

FIX: fix the gimbal relative rotate mode not work bug

---

osdk-core/modules/src/filemgr/impl/dji_file_mgr_impl.cpp

Signed-off-by: DJI-Martin <DJI-Martin@dji.com>

FIX: fix the memory leak when downloading media files

---

osdk-core/modules/src/filemgr/impl/dji_file_mgr_impl.cpp

Signed-off-by: DJI-Martin <DJI-Martin@dji.com>

FIX: fix the download filelist failed issue on M300 RTK
